### PR TITLE
Develop - fixed mavros error in simple_pilot and pilot.cpp - added mavros_msgs include and CommandCode

### PR DESCRIPTION
**Pull request by binary42**
Details: Seems like there was a change to mavros over the last few months. When building on the RPi, noticed build failed giving ActuatorCommand.h not found. Discovered that both ActuatorCommand and CommandLong now live in mavros_msgs:: and not mavros:: scope. Modified both simple_pilot and pilot.cpp for new scoping as well as changed CommandLongRequest to CommandCode for line 79 of simple_pilot: mavros_msgs::CommandCode::CMD_DO_SET_SERVO. Also added include mavros_msgs/CommandCode.h to handle command codes properly. Also removed cached files from editor gedit.

### CODE REVIEW

**Comment by joshvillbrandt** [comment]
Looks good to me! I'll try this out on hardware in the next 24 hours and then merge it in. Thanks, @binary42!

**Comment by binary42** [comment]
Great, yeah I don't have a hardware stack yet for bench testing. Soon...

**Comment by joshvillbrandt** [comment]
I can't merge this anymore because you've continued adding commits to the pull request. However, I'm taking the contents of your original PR and adding it to the repo now. Next time, try making a "feature branch" (something like `fix/mavros-library-update`) so that  you can continue to work on your primary branch without affecting pull requests.

Thanks for the bug fix!

**Comment by binary42** [comment]
oops, sorry, didn't realize I was doing that. Got it, thanks.

**Pull request closed without merging**
