### PR TITLE
fixed mavros error in simple_pilot and pilot.cpp - added mavros_msgs …

### PR DESCRIPTION
**Pull request by binary42**
…include and CommandCode.

Details: Seems like there was a change to mavros over the last few months. When building on the RPi, noticed build failed giving ActuatorCommand.h not found. Discovered that both ActuatorCommand and CommandLong now live in mavros_msgs:: and not mavros:: scope. Modified both simple_pilot and pilot.cpp for new scoping as well as changed CommandLongRequest to CommandCode for line 79 of simple_pilot: mavros_msgs::CommandCode::CMD_DO_SET_SERVO. Also added include mavros_msgs/CommandCode.h to handle command codes properly.

### CODE REVIEW

**Comment by binary42** [comment]
I actually meant to request this to be merged to develop...Not sure how to adjust this unless you want to deny this request and I can resubmit for the develop branch

**Comment by chapulino** [comment]
one more detail

line65 in simple_pilot.cpp
srv.request.command = 183;

I tried and work, Thanks

**Comment by joshvillbrandt** [comment]
Hey @binary42, thanks for this PR! I couple of cleanup suggestions:
- GitHub isn't letting me re-route this request to #develop. Could you please open a new request to that branch?
- Please make sure you do not include your editor's temporary files in the pull request. You can check this doing a `git diff --cached` before you commit your changes.

**Comment by binary42** [comment]
Oh yeah, lol, sorry about that. Sure I'll create a new request. stupid gedit, lol.

**Pull request closed without merging**
